# Generated by Django 5.0.1 on 2024-02-01 21:28

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 2, 1, 21, 28, 45, 652639, tzinfo=datetime.timezone.utc), verbose_name='تاریخ عضویت'),
        ),
    ]
