# Generated by Django 5.0.1 on 2024-02-02 11:11

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_joined_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('expire', models.DateTimeField(null=True)),
                ('used_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 2, 2, 11, 11, 37, 206384, tzinfo=datetime.timezone.utc), verbose_name='تاریخ عضویت'),
        ),
    ]
