# Generated by Django 5.0.1 on 2024-02-02 11:21

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userotp_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 2, 2, 11, 21, 25, 981737, tzinfo=datetime.timezone.utc), verbose_name='تاریخ عضویت'),
        ),
    ]
